INSERT INTO `pharmacy`.`product` (`product_id`, `product_name`, `description`, `category`, `price`, `inventory_id`) 
VALUES ("HEA001","Difflam plus","Difflam Plus Anaesthetic Sore Throat Lozenges have a Triple action Antibacterial + Anti-Inflammatory + Anaesthetic formula","Health","9.99","24"),
("HEA002","Strepsils Extra","It is an advanced formula that does not just have Antibacterial Action, but also numbs the pain of inflamed sore throats","Health","6.79","21"),
("HEA003","Tiger Balm White","For the temporary relief of aches and pains of muscles and joints", "Health","8.99","18"),
("HEA004","NYAL Cold Sore Cream","Soothing! healing! protective relief from the symptoms of cold sores and cracked lips.","Health","9.99","15"),
("HEA005","Thursday Plantation","Antigungal Cream" ,"Health","13.99","12"),
("HEA006","MAGNORUB Magnesium Oil","Premium Grade Transdermal Super-saturated solution of altitude-sourced magnesium for application and absorption through the skin.","Health","29.99","9"),
("HEA007","Bioglan Immunoforce","To support a healthy immune system function and reduce the severity of symptoms of common colds and flu." ,"Health","30.99","6"),	
("BEA001","AUSTRALIS Lipliner Pencil","Soft! easy glide lip pencil for simple precise application to create the perfect lip colour base","beauty","10.99","3"),
("BEA002","OPALLAC Allure Palette","Set contains Plush! Opulent! Lavish and Majestic","beauty",29.45,1),
("BEA003","Liquid Liner","Waterproof and smudge-proof! this liquid dries down to a striking metallic finish and can be used on the face AND body!","beauty",99.99,22),
("BEA004","PACO RABANNE Lady Million","A rose revolution that collapses your boundaries, making room but for pure sensation","beauty",49.99,20),
("BEA005","HASK Curl Care","Replenish moisture and restore strength back into frizzy, damaged strands with this deep conditioning treatment","beauty",5.45,16),
("BEA006","NAPRO Palette","Permanent! intensive caring colour. For Noble Browns with subtle reflexes.","beauty",35.55,14),
("BAT001","DETTOL Foam Hand Wash", "Lime and Orange,Foaming handwash","Bathroom Basics",15.45,10),
("BAT002","Bath Soak","Soothe mind and body with this Midnight Garden Scented Bath Soak","Bathroom Basics",8.99,8),
("BAT003","RADOX Bath Salts","Bath salts with 100% pure sea salt","Bathroom Basics",4.95,4),
("BAT004","FRESH FRUIT SPA Body Wash","Add some frothy fun to bath time with this dual-purpose body wash and bubble bath","Bathroom Basics",29.99,2),
("BAT005","ESSENTIAL BATH Back Brush","Exfoliating bristle brush leaves skin feeling fresh","Bathroom Basics",8.10,5),
("BAT006","GARNIER Beauty Oil Scrub","Discover the nourishing and beautifying power of 4 precious oils - Argan! Macadamia! Almond & Rose - infused in a beauty scrub to visibly transform your skin","Bathroom Basics",12.45,7),
("VIT001","OPTIFAST VLCD Bar Assorted","which contains all of the nutrients required for safe and effective weight loss! including protein to help you preserve lean muscle mass while you lose fat stores","Vitamins",10.99,11),
("VIT002","NATUROPATHICA FatBlaster","Want to achieve your Keto goals faster? Fire up your Keto diet with Keto-Fit Fire" ,"Vitamins",25.99,13),
("VIT003","SWISSE Chlorophyll","Swisse Ultiboost Chlorophyll contains premium quality chlorophyll","Vitamins",4.95,17),
("VIT004","RAPID LOSS Salted Caramel Meal Replacement Shake","High-quality protein meal replacement shake with the decandant flavour of salted caramel","Vitamins",8.10,19),
("VIT005","ATKINS Advantage Fudge", "Caramel Bar!Protein Bar and Satisfying snack on the run","Vitamins",12.95,23),
("VIT006","FREESOUL Steel Shaker","Free Souls Stainless Steel Shaker is the ideal companion for your protein shakes","Vitamins",29.50,7);